name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-22.04  # 👈 Use older runner to avoid upload-artifact@v3 issue

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload static site
        uses: actions/upload-pages-artifact@v2
        with:
          path: "."  # make sure index.html is in the repo root

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
